[settings]
pubchem_attr_etc: logp,pc_iupac_name


[attribute_mapping]
PUBCHEM_COMPOUND_CID: pubchem_id

PUBCHEM_IUPAC_OPENEYE_NAME: names
PUBCHEM_IUPAC_CAS_NAME: names
PUBCHEM_IUPAC_NAME_MARKUP: names
PUBCHEM_IUPAC_NAME: names
PUBCHEM_IUPAC_SYSTEMATIC_NAME: names
PUBCHEM_IUPAC_TRADITIONAL_NAME: names

PUBCHEM_MOLECULAR_FORMULA: formula
PUBCHEM_IUPAC_INCHI: inchi
PUBCHEM_IUPAC_INCHIKEY: inchikey
PUBCHEM_OPENEYE_CAN_SMILES: smiles
PUBCHEM_OPENEYE_ISO_SMILES: smiles

PUBCHEM_XLOGP3: logp
PUBCHEM_EXACT_MASS: mi_mass
PUBCHEM_MOLECULAR_WEIGHT: mass
PUBCHEM_TOTAL_CHARGE: charge

; UNUSED FOR NOW:
PUBCHEM_HEAVY_ATOM_COUNT: atom_count
PUBCHEM_ATOM_DEF_STEREO_COUNT: d1
PUBCHEM_ATOM_UDEF_STEREO_COUNT: d2
PUBCHEM_BOND_DEF_STEREO_COUNT: d3
PUBCHEM_BOND_UDEF_STEREO_COUNT: d4
PUBCHEM_ISOTOPIC_ATOM_COUNT: d5
PUBCHEM_COMPONENT_COUNT: d6
PUBCHEM_CACTVS_TAUTO_COUNT: d7
