[default]
discoverable = true
fetch_api = true
cache_enabled = true
cache_api_result = true

[cas]
discoverable = true
fetch_api = false
cache_enabled = false
cache_api_result = false

[swisslipids]
# not yet supported due to a bug
discoverable = false
