[pubchem]
discoverable = true
fetch_api = false
cache_enabled = true
cache_api_result = false

[chebi]
discoverable = true
fetch_api = true
cache_enabled = true
cache_api_result = false

[hmdb]
discoverable = true
fetch_api = true
cache_enabled = true
cache_api_result = false

[kegg]
discoverable = true
fetch_api = true
cache_enabled = true
cache_api_result = false

[lipmaps]
discoverable = true
fetch_api = true
cache_enabled = true
cache_api_result = false

[cas]
discoverable = true

[chemspider]
discoverable = true

[metlin]
discoverable = true

[inchikey]
discoverable = true

[smiles]
discoverable = false

[swisslipids]
# not yet supported due to a bug
discoverable = false
